server:
  port: 8140 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-cms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos 服务地址
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
  redis:
    host: localhost
    port: 6379
    database: 0
    password: password # 默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认 8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认 -1
        max-idle: 8     #最大空闲连接，默认 8
        min-idle: 0     #最小空闲连接，默认 0

  datasource: # mysql 数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shenlan_cms?serverTimezone=GMT%2B8
    username: username
    password: password
  jackson: #返回 json 的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis 日志
  mapper-locations: classpath:com/zfans/shenlan/service/cms/mapper/xml/*.xml

ribbon:
  ConnectTimeout: 10000 # 连接建立的超时时长，默认 1 秒
  ReadTimeout: 10000 # 处理请求的超时时间，默认为 1 秒

feign:
  sentinel:
    enabled: true